[package]
name = "huus_macros_support"
version = "0.1.0"
authors = ["Wojciech Kluczka <wojciech.kluczka@gmail.com>"]
edition = "2018"

[dependencies]
askama = "0.8.0"
bson = "0.11"
chrono = "0.4.10"
huus = "0.1.0"
lazy_static = "1.4"
proc-macro2 = "1.0"

